#!/bin/bash -l 
GIT_REPO=git@github.com:jaxma/pig.git
TMP_GIT_CLONE=/tmp/pig 
PUBLIC_WWW=/www/wwwroot/pig
rm -rf ${TMP_GIT_CLONE} 
git clone $GIT_REPO $TMP_GIT_CLONE 
cd $TMP_GIT_CLONE 
rm -rf ${PUBLIC_WWW}/* 
cp -rf ${TMP_GIT_CLONE}/* ${PUBLIC_WWW}